### ISSUE TITLE
Regarding ÆØÅ and ascii encoding errors

### ISSUE THREAD

**Issue by atchoo78** [ways/rutercli#5]
Hi,

By a stroke of luck, I just got **rutercli** up and running on my Raspberry Pi  after some frustrating hours. 

I got the infamous 
```
**'ascii' codec can't encode character u'[some unicode]' in position [X] : ordinal not in range(128)**
```
error, with or without the "-a" parameter.

After a quick search, I found out that the characters in question was the unicode variants of  "æ", "ø" and "å" (and _not_ the emojicon/icon representation of the transportation categories, which was my initial thought).🚅

So I tried converting the XML output with "**...decode('utf8')**" in all the appropriate places, but no such luck. 

However, the magic trick that made it work, was changing all of the "locale" variables to "**nb_NO.UTF-8**" instead of "C" like this:

- ``` **sudo raspi-config**  ``` 
- Adding the mentioned locale in the "Localization" menu option.
- Choosing Norwegian/UTF8 as the default language and locale
- And finally ``` LC_ALL="nb_NO.UTF-8" ``` which automatically changes all of the "LC" variables to that value. 
- Logged out/in of SSH, and voilá.

That said, I'm still clueless on how (and if?) to make it run on macOS (High Sierra, latest).
Still getting the "ascii codec can't encode..." error there, and the locale variables and settings are not easily changed or manipulated in osx/macOS. 

I've tried with various Terminal settings for encoding/text, but it seems like I'm stuck for now (that is, unless I use ruterCLI to search for stops that do NOT have "ÆØÅ" in them, without any "påstigning" in the returned info text or "avvik" (in other words: _mission impossible_). 

I tried running your php example, but macOS can't seem to find python3 in **/usr/bin/env**, despite having changed the PYTHONPATH and so on.

Any ideas?

Best regards 👾
Andreas

**Comment by ways** [comment]
I don't have a mac to test on. =/

> By a stroke of luck, I just got rutercli up and running on my Raspberry Pi after some frustrating hours.

Anything I can do to make it easier for the next guy?

**Comment by atchoo78** [comment]
Yes! Just got it working, so you can include my guide for the next guy:

- Install Python 3 via Homebrew
```
brew install python3
```
```
sudo pip3 install tabulate
sudo pip3 install colors 
```
- Close any open Terminal windows
- Edit ~/.bash_profile:
```
export LC_ALL="nb_NO.utf-8"
export LANG="nb_NO.utf-8"
export LC_COLLATE="nb_NO.utf-8"
export LC_CTYPE="nb_NO.utf-8"
export LC_MESSAGES="nb_NO.utf-8"
export LC_MONETARY="nb_NO.utf-8"
export LC_NUMERIC="nb_NO.utf-8"
export LC_TIME="nb_NO.utf-8"
export PYTHONPATH="${PYTHONPATH}:/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python"
export PYTHONIOENCODING=UTF-8
export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/sbin:$PATH
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
```
- From a terminal window, type 
```
which python3 
```
If it returns "/usr/local/bin/python3", everything is correctly installed so far.
```
./ruter.py "helsfyr [t-bane]"
```
![skjermbilde 2](https://user-images.githubusercontent.com/20549049/39766374-6be602da-52e4-11e8-855d-1d3ad837a32d.png)

BTW: You should check out [Easy Autocomplete](http://easyautocomplete.com/) for the web wrapper version :) 

Cheers, Andreas

**Comment by atchoo78** [comment]
PS: And refer to my previous/first post regarding making it easier for the next Linux guy :-D

**Comment by ways** [comment]
Thanks, added to readme and install files.
